export interface LibroBiblia {
  orden: number
  nombre: string
  referencia: string
  capitulos: number
  testamento: 'antiguo' | 'nuevo'
}

export const LIBROS_BIBLIA: LibroBiblia[] = [
  { orden: 1, nombre: 'Génesis', referencia: 'Genesis', capitulos: 50, testamento: 'antiguo' },
  { orden: 2, nombre: 'Éxodo', referencia: 'Exodus', capitulos: 40, testamento: 'antiguo' },
  { orden: 3, nombre: 'Levítico', referencia: 'Leviticus', capitulos: 27, testamento: 'antiguo' },
  { orden: 4, nombre: 'Números', referencia: 'Numbers', capitulos: 36, testamento: 'antiguo' },
  { orden: 5, nombre: 'Deuteronomio', referencia: 'Deuteronomy', capitulos: 34, testamento: 'antiguo' },
  { orden: 6, nombre: 'Josué', referencia: 'Joshua', capitulos: 24, testamento: 'antiguo' },
  { orden: 7, nombre: 'Jueces', referencia: 'Judges', capitulos: 21, testamento: 'antiguo' },
  { orden: 8, nombre: 'Rut', referencia: 'Ruth', capitulos: 4, testamento: 'antiguo' },
  { orden: 9, nombre: '1 Samuel', referencia: '1 Samuel', capitulos: 31, testamento: 'antiguo' },
  { orden: 10, nombre: '2 Samuel', referencia: '2 Samuel', capitulos: 24, testamento: 'antiguo' },
  { orden: 11, nombre: '1 Reyes', referencia: '1 Kings', capitulos: 22, testamento: 'antiguo' },
  { orden: 12, nombre: '2 Reyes', referencia: '2 Kings', capitulos: 25, testamento: 'antiguo' },
  { orden: 13, nombre: '1 Crónicas', referencia: '1 Chronicles', capitulos: 29, testamento: 'antiguo' },
  { orden: 14, nombre: '2 Crónicas', referencia: '2 Chronicles', capitulos: 36, testamento: 'antiguo' },
  { orden: 15, nombre: 'Esdras', referencia: 'Ezra', capitulos: 10, testamento: 'antiguo' },
  { orden: 16, nombre: 'Nehemías', referencia: 'Nehemiah', capitulos: 13, testamento: 'antiguo' },
  { orden: 17, nombre: 'Ester', referencia: 'Esther', capitulos: 10, testamento: 'antiguo' },
  { orden: 18, nombre: 'Job', referencia: 'Job', capitulos: 42, testamento: 'antiguo' },
  { orden: 19, nombre: 'Salmos', referencia: 'Psalms', capitulos: 150, testamento: 'antiguo' },
  { orden: 20, nombre: 'Proverbios', referencia: 'Proverbs', capitulos: 31, testamento: 'antiguo' },
  { orden: 21, nombre: 'Eclesiastés', referencia: 'Ecclesiastes', capitulos: 12, testamento: 'antiguo' },
  { orden: 22, nombre: 'Cantares', referencia: 'Song of Songs', capitulos: 8, testamento: 'antiguo' },
  { orden: 23, nombre: 'Isaías', referencia: 'Isaiah', capitulos: 66, testamento: 'antiguo' },
  { orden: 24, nombre: 'Jeremías', referencia: 'Jeremiah', capitulos: 52, testamento: 'antiguo' },
  { orden: 25, nombre: 'Lamentaciones', referencia: 'Lamentations', capitulos: 5, testamento: 'antiguo' },
  { orden: 26, nombre: 'Ezequiel', referencia: 'Ezekiel', capitulos: 48, testamento: 'antiguo' },
  { orden: 27, nombre: 'Daniel', referencia: 'Daniel', capitulos: 12, testamento: 'antiguo' },
  { orden: 28, nombre: 'Oseas', referencia: 'Hosea', capitulos: 14, testamento: 'antiguo' },
  { orden: 29, nombre: 'Joel', referencia: 'Joel', capitulos: 3, testamento: 'antiguo' },
  { orden: 30, nombre: 'Amós', referencia: 'Amos', capitulos: 9, testamento: 'antiguo' },
  { orden: 31, nombre: 'Abdías', referencia: 'Obadiah', capitulos: 1, testamento: 'antiguo' },
  { orden: 32, nombre: 'Jonás', referencia: 'Jonah', capitulos: 4, testamento: 'antiguo' },
  { orden: 33, nombre: 'Miqueas', referencia: 'Micah', capitulos: 7, testamento: 'antiguo' },
  { orden: 34, nombre: 'Nahúm', referencia: 'Nahum', capitulos: 3, testamento: 'antiguo' },
  { orden: 35, nombre: 'Habacuc', referencia: 'Habakkuk', capitulos: 3, testamento: 'antiguo' },
  { orden: 36, nombre: 'Sofonías', referencia: 'Zephaniah', capitulos: 3, testamento: 'antiguo' },
  { orden: 37, nombre: 'Hageo', referencia: 'Haggai', capitulos: 2, testamento: 'antiguo' },
  { orden: 38, nombre: 'Zacarías', referencia: 'Zechariah', capitulos: 14, testamento: 'antiguo' },
  { orden: 39, nombre: 'Malaquías', referencia: 'Malachi', capitulos: 4, testamento: 'antiguo' },
  { orden: 40, nombre: 'Mateo', referencia: 'Matthew', capitulos: 28, testamento: 'nuevo' },
  { orden: 41, nombre: 'Marcos', referencia: 'Mark', capitulos: 16, testamento: 'nuevo' },
  { orden: 42, nombre: 'Lucas', referencia: 'Luke', capitulos: 24, testamento: 'nuevo' },
  { orden: 43, nombre: 'Juan', referencia: 'John', capitulos: 21, testamento: 'nuevo' },
  { orden: 44, nombre: 'Hechos', referencia: 'Acts', capitulos: 28, testamento: 'nuevo' },
  { orden: 45, nombre: 'Romanos', referencia: 'Romans', capitulos: 16, testamento: 'nuevo' },
  { orden: 46, nombre: '1 Corintios', referencia: '1 Corinthians', capitulos: 16, testamento: 'nuevo' },
  { orden: 47, nombre: '2 Corintios', referencia: '2 Corinthians', capitulos: 13, testamento: 'nuevo' },
  { orden: 48, nombre: 'Gálatas', referencia: 'Galatians', capitulos: 6, testamento: 'nuevo' },
  { orden: 49, nombre: 'Efesios', referencia: 'Ephesians', capitulos: 6, testamento: 'nuevo' },
  { orden: 50, nombre: 'Filipenses', referencia: 'Philippians', capitulos: 4, testamento: 'nuevo' },
  { orden: 51, nombre: 'Colosenses', referencia: 'Colossians', capitulos: 4, testamento: 'nuevo' },
  { orden: 52, nombre: '1 Tesalonicenses', referencia: '1 Thessalonians', capitulos: 5, testamento: 'nuevo' },
  { orden: 53, nombre: '2 Tesalonicenses', referencia: '2 Thessalonians', capitulos: 3, testamento: 'nuevo' },
  { orden: 54, nombre: '1 Timoteo', referencia: '1 Timothy', capitulos: 6, testamento: 'nuevo' },
  { orden: 55, nombre: '2 Timoteo', referencia: '2 Timothy', capitulos: 4, testamento: 'nuevo' },
  { orden: 56, nombre: 'Tito', referencia: 'Titus', capitulos: 3, testamento: 'nuevo' },
  { orden: 57, nombre: 'Filemón', referencia: 'Philemon', capitulos: 1, testamento: 'nuevo' },
  { orden: 58, nombre: 'Hebreos', referencia: 'Hebrews', capitulos: 13, testamento: 'nuevo' },
  { orden: 59, nombre: 'Santiago', referencia: 'James', capitulos: 5, testamento: 'nuevo' },
  { orden: 60, nombre: '1 Pedro', referencia: '1 Peter', capitulos: 5, testamento: 'nuevo' },
  { orden: 61, nombre: '2 Pedro', referencia: '2 Peter', capitulos: 3, testamento: 'nuevo' },
  { orden: 62, nombre: '1 Juan', referencia: '1 John', capitulos: 5, testamento: 'nuevo' },
  { orden: 63, nombre: '2 Juan', referencia: '2 John', capitulos: 1, testamento: 'nuevo' },
  { orden: 64, nombre: '3 Juan', referencia: '3 John', capitulos: 1, testamento: 'nuevo' },
  { orden: 65, nombre: 'Judas', referencia: 'Jude', capitulos: 1, testamento: 'nuevo' },
  { orden: 66, nombre: 'Apocalipsis', referencia: 'Revelation', capitulos: 22, testamento: 'nuevo' },
]
