export { gastosRepository } from './gastos.repository'
export { gastosFijosRepository } from './gastos-fijos.repository'
export { tarjetasRepository } from './tarjetas.repository'
export { planesCuotasRepository, cuotasMensualesRepository } from './cuotas.repository'
export { abonosTarjetaRepository } from './abonos.repository'
export { montosManualesRepository } from './montos-manuales.repository'
export { ingresosRepository } from './ingresos.repository'
export { categoriasRepository } from './categorias.repository'
